version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8080"
    volumes:
      - app-logs:/var/log

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  app-logs:
